### ISSUE TITLE
Question for procedural_color.glsl

### ISSUE THREAD

**Issue by ptanugra** [alecjacobson/computer-graphics-shader-pipeline#11]
I think I have finish implementing the peril_noise correctly, however i'm not sure how I'm supposed to get the same exact pattern as the one in the Readme. Also, I am not fully sure on what is expected to earn full marks?

Are we required to mimic exactly the drawing to get full marks or as long as we can show how to manipulate or change the texture of the planet we are good?

Or can you give some guidance in order to verify that we have the correct implementation? Thanks!

**Comment by ptanugra** [comment]
I ended up just creating my own marble like sphere try and make it as close to the readme (it definitely has the marble-like structure)
But just want to confirm that this is okay

**Comment by alecjacobson** [comment]
Be creative. It also doesn’t need to be a marble texture.
