### ISSUE TITLE
Very difficult to read math equations

### ISSUE THREAD

**Issue by ptanugra** [alecjacobson/computer-graphics-shader-pipeline#13]
I find that the math equations for this lab's extremely difficult to read. (Ex: in the bump mapping section) I have also tried reading from the source README.md but I also still find it difficult to read as it is cluttered with cryptic symbols like mathbf, \\, weird spacings and all that. 

Are there outside references in which we could get the equations from? If not, how can we improve the readability of the math equations in the readme? 

This same issue was already brought up by multiple students since the first assignment during the tutorial session but the TA's just told us to try and read from the source README. 

Thanks!

**Comment by alecjacobson** [comment]
You should open the README.html

**Comment by ptanugra** [comment]
Thanks!
