### ISSUE TITLE
error: file has changed since the latest compilation

### ISSUE THREAD

**Issue by Madach97** [alecjacobson/computer-graphics-shader-pipeline#16]
When I run the executable on Visual Studio in Windows, opengl reports it cannot read the "test-01.json" file and says "file has changed since the latest compilation attempt". I didn't change the file at all. I also tried doing a clean build of all the files again and then running the application but still no luck, I get the same message.

Anyone know how to fix this?

**Comment by alecjacobson** [comment]
Duplicate of https://github.com/alecjacobson/computer-graphics-shader-pipeline/issues/2
