### ISSUE TITLE
Different color when running test-01

### ISSUE THREAD

**Issue by zilixie** [alecjacobson/computer-graphics-shader-pipeline#17]
<img width="639" alt="screen shot 2018-11-08 at 8 41 35 pm" src="https://user-images.githubusercontent.com/22263748/48237895-ca187480-e396-11e8-9402-84df85412046.png">

Hi everyone,
When I am testing with test-01.json, instead of the image shown in README, I get this image. Could this mean that my OpenGL setup isn't correct?

Has anyone come with this?

**Comment by RioAraki** [comment]
+1

**Comment by Ian729** [comment]
+1

**Comment by Ian729** [comment]
+2

**Comment by alecjacobson** [comment]
This should be fixed now in the readme (your images are correct).
