### ISSUE TITLE
bump.fs understanding 

### ISSUE THREAD

**Issue by ptanugra** [alecjacobson/computer-graphics-shader-pipeline#18]
Hi Professor,

For bump.fs, I have followed all of the instructions and steps to calculate the normal (also Implemented the improved perlin noise). However i keep on getting a completely different result than the one in the README. Also with openGL, it's significantly harder to debug (can't simply print values on screen).
Here is a screenshot of my completely wrong results:
![screen shot 2018-11-08 at 9 00 28 pm](https://user-images.githubusercontent.com/43912335/48238533-588df580-e399-11e8-9c17-bd11a4430044.png)

I have also researched into setting up a TBN matrix but to no avail, it still produces a completely different result. I feel like I'm getting stuck in a loop trying after trying to read the many different articles online back and forth and the book doesn't really touch upon this topic either. 

Am I going in the right direction? Also, am I overthinking the problem?

**Comment by ptanugra** [comment]
I think i got it

**Comment by RioAraki** [comment]
Hi, I also have a really hard time debugging this. I thought I have implement everything from readme and get a bumpy effect, but my output looks very similar to yours especially how the sphere is split up with edges to colors. May you share how you figure it out?

Here is my current normal output:
![2018-11-12-165748_628x363_scrot](https://user-images.githubusercontent.com/19270277/48377553-241d8080-e69c-11e8-9f26-ef9bcc80b48d.png)

Thanks in advance!

**Comment by RioAraki** [comment]
To answer my own question, the multiplication sign in the mathematic formula meant to be a cross product, it is not a multiplication!
