### ISSUE TITLE
procedural_color.glsl

### ISSUE THREAD

**Issue by zhtdavis** [alecjacobson/computer-graphics-shader-pipeline#21]
after I add perlin noise offset, I get something like 
<img width="200" alt="screen shot 2018-11-09 at 11 31 41 pm" src="https://user-images.githubusercontent.com/15790615/48297495-cc9ecb00-e477-11e8-809e-ada391ea356a.png">

I can see a line through the sphere. Is it normal to see a line like this?

**Comment by ptanugra** [comment]
Hmm probably not, you might have broken some "continuity" in your code.

**Comment by psarahdactyl** [comment]
What was the problem?
