### ISSUE TITLE
shader 'pos_fs_in' not read by fragment shader

### ISSUE THREAD

**Issue by coolKev666** [alecjacobson/computer-graphics-shader-pipeline#22]
When I tried running ./shaderpipeline ../data/test-03.json, I received the following warning:

'''
WARNING: Output of tessellation evaluation shader 'pos_fs_in' not read by fragment shader

shader compilation successful.
'''

As a result, I was unable to see through the object. Any ideas why?
Btw, running on mac 10.13.6.

<img width="308" alt="screen shot 2018-11-10 at 3 17 39 am" src="https://user-images.githubusercontent.com/40505637/48299159-19de6500-e497-11e8-94d0-ab9db54355f5.png">

**Comment by ptanugra** [comment]
I think you can safely ignore this as long as you are generating the correct image. 
It just means that the variable pos_fs_in which was declared as an output is not being used in your fragment shader.
