### ISSUE TITLE
Question about "model.glsl" and "model_view_projection.vs"

### ISSUE THREAD

**Issue by songfeil** [alecjacobson/computer-graphics-shader-pipeline#23]
Hi,

I'm wondering if there should be another translation "t" input for the model function, since model expects translate and "model_view_projection.vs" only expects model.
Or should we just hard code the translating unit into the file.

Thanks.

**Comment by ZhuaMei** [comment]
hardcode.

**Comment by nafis95** [comment]
you can also call translation() and uniform_scalar() function from model_view_projection file and use that to find the combined transformation for the moon
