### ISSUE TITLE
MarkUs Submission for this lab not posted yet?

### ISSUE THREAD

**Issue by ptanugra** [alecjacobson/computer-graphics-shader-pipeline#25]
^^

**Comment by psarahdactyl** [comment]
Just posted

**Comment by ptanugra** [comment]
Ehh there are a few missing files .. 
Such as 5.tcs, blinn_phong.glsl , blue_and_gray.fs ..

@psarahdactyl

**Comment by ptanugra** [comment]
Can you please reopen the issue until its fully fixed, so that this is visible to other people as well.

Thanks!
