### ISSUE TITLE
model.glsl Speed of animation

### ISSUE THREAD

**Issue by Marina-t** [alecjacobson/computer-graphics-shader-pipeline#27]
Does it matter how fast/slow we make the animation run or should the moon finish a full rotation and a full revolution in a specific number of seconds?

Thanks

**Comment by ZhuaMei** [comment]
see model_view_projection.glsl

**Comment by cheshmi** [comment]
No, the running time of your code does not have any effect on your grade. However, the animation duration has to follow the instruction in model_view_projection.glsl .
