### ISSUE TITLE
Perlin Noise

### ISSUE THREAD

**Issue by AbdallaGomaa** [alecjacobson/computer-graphics-shader-pipeline#28]
For perlin noise, there's the hash function P that maps to a number from 0 - 256 and then the output of that is then the input to G. I found that there's a preset P array with a specific permutation of the numbers from 0 -256 but when I try to use that, the shader is super slow. Are we supposed to use random_direction instead of G[P[i+P[j+P[k]]]? I know in the improved version we don't have to generate a random output of G but we still need to use P and I don't know how I can use an array of numbers unless a texture is created and passed into the fragment shader which I don't think we can do.

**Comment by alecjacobson** [comment]
Yes, it's fine to just use `random_direction`

**Comment by ptanugra** [comment]
@AbdallaGomaa try making the array to a const type.

**Comment by ptanugra** [comment]
for some reason with my computer (Macbook Air), adding the const increases the speed. 
But when I searched online, it appears to be the opposite for some people. Then I found this stackoverflow issue which states that it may depend on your hardware driver.

https://stackoverflow.com/questions/21859433/glsl-const-array-pros

**Comment by AbdallaGomaa** [comment]
Yeah I tried running on a Macbook Pro and on WebGL and it was extremely slow but I think we can just use `random_direction` as the professor mentioned. I just don't know how that works with the 2nd improvement in Perlin Noise unless we just ignore it and only implement the updated gradient function.

**Comment by alecjacobson** [comment]
You can just use the improved smooth step.


>
>
