### ISSUE TITLE
Smooth Heavside

### ISSUE THREAD

**Issue by AbdallaGomaa** [alecjacobson/computer-graphics-shader-pipeline#29]
What's the range of this function? -1 - 1? Are we supposed to use the output of the `perlin_noise` as the input of this function?

**Comment by ZhuaMei** [comment]
I'm confused by this function, and I am not sure what we should implement.

**Comment by cheshmi** [comment]
It should be in the range of [0,1]. 
You can use it for making funky noises wherever is needed.
