### ISSUE TITLE
ReadMe typo?

### ISSUE THREAD

**Issue by ptanugra** [alecjacobson/computer-graphics-shader-pipeline#3]
Under the topic Tesselation Control Shader...
" the number of new edges each input each should split into (gl_TessLevelOuter[1] = 5 means the edge across from vertex 0 (i.e., the edge between vertices 0 and 2) should be split into 5 edges); "

Do you mean "the edge across from vertex 1 " instead?

**Comment by alecjacobson** [comment]
was fixed in b3321192bbf4e90646ce8f3d21804f30725cac22
