### ISSUE TITLE
Adding Perlin Noise to Texture

### ISSUE THREAD

**Issue by coolKev666** [alecjacobson/computer-graphics-shader-pipeline#31]
Once we calculate the perlin noise value, how do we add it to our color texture? 
Say I already have obtained a vec3 color vector by calling bling-phong, how do I append my noise value to the color vector?

**Comment by AbdallaGomaa** [comment]
You can use mix on kd. Try something like mix(kd, vec3(1), noise)

**Comment by coolKev666** [comment]
So mix will give an interpolated new kd value based on noise right? Also, what is the seed vector that we have to pass into the perlin_noise function? Is it simply the position of a point on the unit sphere?

**Comment by AbdallaGomaa** [comment]
Yeah mix will interpolate the kd value between what it originally was and whatever color you choose based on the noise. And yeah I just used the position of the point on the sphere as my seed but you can use time for example if you wanted to, which we're meant to do in planet.fs
