### ISSUE TITLE
Clarification on Functions to Implement

### ISSUE THREAD

**Issue by AkilasZ** [alecjacobson/computer-graphics-shader-pipeline#33]
Good evening,

Just to clarify, are we supposed to:
1) Implement tangent.glsl
2) Not implement smooth_heaviside.glsl

I don't recall using anything that would need smooth_heaviside, but it is part of the MarkUs submission list and tangent is not. Can I get a clarification on what actually needs to be done?

Thanks,
- A.T.

**Comment by ptanugra** [comment]
Good question. 
There seems to be a lot of file missing in the MarkUs. The TAs are not responding either to one of my previous comments in the closed issue section.

**Comment by psarahdactyl** [comment]
My bad.
