### ISSUE TITLE
Smooth Normal transition

### ISSUE THREAD

**Issue by Marina-t** [alecjacobson/computer-graphics-shader-pipeline#39]
This relates to the snap_to_sphere implementation,
When I debug by mapping the color based on the normal value, I get a very faceted appearance and I am not sure how to get the normals of neighboring triangles so I can have a smoother transition.
does pos_es_in contain all of the neighboring triangles' vertices?

thanks

**Comment by nafis95** [comment]
In snap_to_sphere, the normal of the sphere should just be the point (since centre is origin). So you should not need to evaluate neighbouring triangles. Make sure to multiply the normal with inverse transpose matrices to get normal_fs_in
