### ISSUE TITLE
model.glsl

### ISSUE THREAD

**Issue by zhtdavis** [alecjacobson/computer-graphics-shader-pipeline#4]
In seems in readme, it it missing this file but we need to implement this one...

**Comment by alecjacobson** [comment]
Do you mean this one? https://github.com/alecjacobson/computer-graphics-shader-pipeline/blob/master/src/model.glsl

**Comment by zhtdavis** [comment]
Yes

**Comment by alecjacobson** [comment]
Ah, I see what you mean: It was not mentioned in the README.  Now it is.
