### ISSUE TITLE
Output Verification of part 06 and 07

### ISSUE THREAD

**Issue by ghiacciozero** [alecjacobson/computer-graphics-shader-pipeline#41]
For test-06 and test-07, do we need to generate the completely same output animation as it is on the website to get full mark? More specifically, do we need to create the exact same marble texture in part 06 and the bumpy appearance of planet in part 07 as the sample animation?

**Comment by cheshmi** [comment]
No, the marble pattern and bumpy appearance do not need to be the same. As far as you could create some acceptable patterns, that is enough.

**Comment by ptanugra** [comment]
Just making sure that it also does not have to be a marble texture .. Professor mentioned in this closed issue that it could be anything creative @cheshmi 
https://github.com/alecjacobson/computer-graphics-shader-pipeline/issues/11#issuecomment-437001799

**Comment by cheshmi** [comment]
Thanks for the clarification. Does not need to be marble texture.
