### ISSUE TITLE
Tangent calculation

### ISSUE THREAD

**Issue by chris-sky** [alecjacobson/computer-graphics-shader-pipeline#42]
How can we find the tangent vector when we don't have access to the other vertices in the fragment shader? I am given the unit normal vector n = (n1,n2,n3) and only know that n1(x-x0)+n2(y-y0)+n3(z-z0)=0 for some point (x0,y0,z0) on the tangent plane. Please help!

**Comment by RioAraki** [comment]
Any vector orthognal to the N we have would lie on the tangent plane. So the problem really is given N, how do we find an orthognal vector
