### ISSUE TITLE
Could not initialize glfw

### ISSUE THREAD

**Issue by kamoflex** [alecjacobson/computer-graphics-shader-pipeline#46]
When I tried running `./shaderpipeline ../data/test-01.json` on CDF machines I got.
```
No protocol specified
Could not initializing glfw
```
Any thoughts?

**Comment by abhimadan** [comment]
Are you trying this over ssh? If you are, make sure you're passing the `-Y` flag to enable X forwarding (and make sure that you have an X server installed). If it still doesn't work, I'd recommend working on this on your local machine or going to one of the teaching labs.

**Comment by kamoflex** [comment]
I was working on a physical CDF machine.

**Comment by abhimadan** [comment]
Can you check that the packages listed at the bottom of [this page](https://github.com/alecjacobson/computer-graphics-raster-images) are installed? If not, you'll need to install them on that machine.

**Comment by abhimadan** [comment]
Also, can you please provide the full error message you saw?

**Comment by kamoflex** [comment]
I deleted the repo, cloned again and it worked but only on the default terminal, not in the built-in IDE terminal.
