### ISSUE TITLE
Blinn-Phong Specular Location

### ISSUE THREAD

**Issue by Kyaels** [alecjacobson/computer-graphics-shader-pipeline#49]
For the Blinn-Phong shading, I noticed that my specular highlight doesn't seem to be appearing in the centre of the diffuse coloured section (though moving the view around also moved the specular highlight around). I'm wondering if this is something that I'm doing wrong, or if it's just like that (the gif in the readme also seems to have the same issue).

![planet](https://user-images.githubusercontent.com/17801986/68423964-08df3700-0171-11ea-914d-7c65b15eb1b7.png)

**Comment by abhimadan** [comment]
Remember that the position of the specular highlight is view dependent (i.e., it moves in space if you move the eye position), while the diffuse colour is view independent as it's entirely determined by the surface position and the light position. In general, the specular highlight won't be right in the center of the diffuse region.
