### ISSUE TITLE
model_view_projection.vs

### ISSUE THREAD

**Issue by zhtdavis** [alecjacobson/computer-graphics-shader-pipeline#5]
in model.glsl, it says "expects: identity, rotate_about_y, translate, PI"

in my mode_view_projection.cpp, I can only get the correct picture if I do something like 
proj * view * (model * vec4(pos_vs_in, 1.0) + translation);

so in my model.glsl, I do "rotate_about_y, scaling" instead. 

Am I doing anything wrong here?

**Comment by DavidCollard** [comment]
You shouldn't be adding your translation matrix to the modeled position. Transformation matrices are meant to be multiplied into each other, and if you do multiply your matrices together, you can trivially stick it in the model.
