### ISSUE TITLE
Issues on running assignment in Windows

### ISSUE THREAD

**Issue by s99090** [alecjacobson/computer-graphics-shader-pipeline#50]
I cmake this assignment with windows but when I ran the assignment I received:
```
PS computer-graphics-shader-pipeline\build_windows\Release> .\shaderpipeline.exe ..\..\data\test-01.json

Usage:
  [Click and drag]  to orbit view
  [Scroll]  to translate view in and out
  A,a  toggle animation
  L,l  toggle wireframe rending
  Z,z  reset view to look along z-axis
OpenGL version recieved: 3.2.0
Supported OpenGL is 3.2.0 - Build 23.20.16.4973
Supported GLSL is 1.50 - Build 23.20.16.4973
..\..\data\test-01.json has changed since last compilation attempt.
-----------------------------------------------

```
there is a black window popping up but then it stuck there with no errors. Do I miss anything here?

And I have installed OpenGL Extensions Viewer, it says the OpenGL Version is 4.5, but why is the OpenGL version recieved is 3.2.0? is that a problem?

**Comment by abhimadan** [comment]
Did you install the latest OpenGL drivers?

**Comment by s99090** [comment]
i think so, how should I install the drivers? I updated all my existing drivers.

**Comment by s99090** [comment]
I believe my graphics card drivers are all the latest.

**Comment by abhimadan** [comment]
Try changing these lines in `main.cpp` to be 4.0:
https://github.com/alecjacobson/computer-graphics-shader-pipeline/blob/a1a9e1624be173bad222cd4928e1fa71578502f5/main.cpp#L73-L74

Usually OpenGL uses this as the minimum version to pick, but it doesn't seem to want to pick a later version in your case. Please let me know if that works for you so I can update the main repo accordingly.

**Comment by s99090** [comment]
It did use the OpenGL version 4.4 which is great, but it still stuck at the same place, it seems like the shader is not compiling? or what are the other reasons?
```
PS .\shaderpipeline.exe ..\..\data\test-01.json

Usage:
  [Click and drag]  to orbit view
  [Scroll]  to translate view in and out
  A,a  toggle animation
  L,l  toggle wireframe rending
  Z,z  reset view to look along z-axis
OpenGL version recieved: 4.4.0
Supported OpenGL is 4.4.0 - Build 23.20.16.4973
Supported GLSL is 4.40 - Build 23.20.16.4973
..\..\data\test-01.json has changed since last compilation attempt.
-----------------------------------------------

```

**Comment by rarora7777** [comment]
Run from the build folder, not the `Release` or `Debug` folder.

`PS ./Release/shaderpipeline.exe ../data/test-01.json`

**Comment by s99090** [comment]
> Run from the build folder, not the `Release` or `Debug` folder.
> 
> `PS ./Release/shaderpipeline.exe ../data/test-01.json`

Awesome!!!!!!! Thanks so much!!!! mine is working now....

**Comment by s99090** [comment]
I encountered another issue...
When I ran test-03 which require the tessellation shaders, I only got the following graph and it is flashing all the time:
![image](https://user-images.githubusercontent.com/28720546/68500532-e9f0ab80-0229-11ea-8ec5-fdddb080da6c.png)

Any solution for this?
sorry for so many issues happening in the windows system......

**Comment by abhimadan** [comment]
Are you sure this is a Windows issue and not a bug in your shader code? The first two tests use tessellation shaders as well (see `pass_through.tcs` and `pass_through.tes`), so if you didn't have problems there, I don't think it's an issue with your setup.

**Comment by s99090** [comment]
oh really? but I haven't implemented any code for this test-03 yet, my friend who is using macOS can run this one with no problems.

**Comment by s99090** [comment]
I think my issue here is that the output is flashing all the time.

**Comment by s99090** [comment]
NVM, after I implemented the code, it is good now. Thanks a lot.
