### ISSUE TITLE
Distance to the camera in the z-direction debugging Question

### ISSUE THREAD

**Issue by AdaDong05** [alecjacobson/computer-graphics-shader-pipeline#54]
Hi, for the distance debugging method, if I use the same formula in the README, will get a black picture, but if I change the -3 to -5 or lower, I will get a reasonable picture, I wonder am I doing something wrong or the number here does not matter? Thx!

**Comment by abhimadan** [comment]
In `main.cpp`, you'll notice that the view matrix places the camera at `(0, 0, -10)`, so the formula in the readme would map the front hemisphere of the big sphere (with z values in view space from -9 to -10) to -0.2 to -0.4, which will be clamped to 0 and show up as black. So your code is probably fine and it's our formula in the readme that's incorrect for this particular camera position.
