### ISSUE TITLE
About the operation order with vec4 to mat4, with weird performance of translation matrix

### ISSUE THREAD

**Issue by zhufyaxel** [alecjacobson/computer-graphics-shader-pipeline#56]
In both of the textbook, we assume the position vector is a column vector such that for some matrix calculation, things work like
**P' = M * P**
From the GLSL_Programming Wiki, the book claimed that the `vec3/4` should be the column vector as example shows: 
[https://en.wikibooks.org/wiki/GLSL_Programming/Vector_and_Matrix_Operations](https://en.wikibooks.org/wiki/GLSL_Programming/Vector_and_Matrix_Operations)
But after some painful trial, it seems like the translation matrix works in a weird way, as two examples below show:

In this one, we put all the matrix into the way like **P' = P * M**
![image](https://user-images.githubusercontent.com/13378632/68524767-a6815600-0298-11ea-8725-3d745c2f687f.png)
This gave us the proper results we want as below
![image](https://user-images.githubusercontent.com/13378632/68524795-fcee9480-0298-11ea-84b2-bcb570684239.png)
Which from the wiki, means the `vec4` was first transferred into its Transverse and then make the calculation done.
But this should not work properly, as if we have a row vect4 (x, y, z, 1) and left multipy this with the mat4 as
1, 0, 0, 2
0, 1, 0, 0
0, 0, 1, 0
0, 0 ,0 ,1
The results should be (x, y, z, 2x + 1)

In the second one, we put all the matrix as the way of P' = M * P, which is something we should by default do as below shows:
![image](https://user-images.githubusercontent.com/13378632/68524863-a3d33080-0299-11ea-8cb3-20f5092b9bea.png)
Which should be the way to do things but turned out to be something weird like:
![image](https://user-images.githubusercontent.com/13378632/68524868-c06f6880-0299-11ea-8db1-081c55f0b20e.png)
if we don't apply the scaling,the "translate" will be even worse as below:
![image](https://user-images.githubusercontent.com/13378632/68524876-df6dfa80-0299-11ea-9019-c26767c20e12.png)

I've tested in a mac and windows and the same thing occurs here. Seems like the order of rotation and scaling doesn't matter if we do P' = M * P or P' = P * M. Only the translation matrix counter this issue.

But this is so weird, and also, the test with proj and view proved that vec4 should be a column vector, as the only proper way to make the render as expected is something like
`pos_cs_in = proj * view * target;` where `target` is the calculated vec4. This means the `vec4` should be a column vector and a reverse way to do so won't provide wanted results.

Please help to tell me if I understand something wrong in implementations, especially basic translation, rotation and scaling should not be a problem here.

Regards

**Comment by Kyaels** [comment]
First of all, I advise against pasting code here. Academic honesty issues and all that.

Second, take a look at this from the same page you linked:
![image](https://user-images.githubusercontent.com/17801986/68528907-95e7d480-02c6-11ea-9fb9-a76d8bd9d997.png)
The constructor is _column ordered_, not row ordered. Since multiplying the vector on the left is the same as multiplying by the transposed matrix on the right (as seen somewhere on that page), the behaviour looks correct. You can fix this by manually transposing your translate matrix.

**Comment by zhufyaxel** [comment]
Hi Kyaels

Thank you for your reply and the point, this works for my conditions
And I think you are right as pay attention to academic honesty issues here.
