### ISSUE TITLE
colour when not facing the light

### ISSUE THREAD

**Issue by s99090** [alecjacobson/computer-graphics-shader-pipeline#59]
![image](https://user-images.githubusercontent.com/28720546/68547883-040ac500-03b5-11ea-8c57-2b0faf0aafae.png)
The above pic is taken when the light is shooting behind the object, however, we can still see the colour and the specular light on the surface. I guess the terrain will reflect some light but is it too much? Just wonder if those colours are reasonable, or is there something I might implement wrong?

FYI, when I turn off the specular light, the light spots will be gone. However, I am not able to make the dark blue-ish colour on the terrain disappear.

**Comment by abhimadan** [comment]
Remember that there is still an ambient light term that you need to include. Even if the light is behind the sphere, the sphere shouldn't be completely black.

**Comment by s99090** [comment]
yes, I included ambient light and hard code it to a very small number. what about those light points? are they correct?

**Comment by abhimadan** [comment]
If you're confident that you implemented Blinn-Phong shading correctly, then this behaviour is coming from your bump mapped normals. Try changing the colour to show the normals and see if the output makes sense (though please spend some time to think about the output yourself and only ask here if you're really stuck, as that's the best way to learn the material).

**Comment by s99090** [comment]
Thanks!
