### ISSUE TITLE
Noise-displaced Superquadric in classic Perlin Noise methods 

### ISSUE THREAD

**Issue by zhufyaxel** [alecjacobson/computer-graphics-shader-pipeline#61]
As we have a step for improving noise, so here I'm wondering if we applied the classic Perlin noise, should the superquadric phoneme be common and expected (like the figure below),  or that is something wrong with implementation and should be avoided for `perlin_noise.glsl` ? 

![image](https://user-images.githubusercontent.com/13378632/68568795-90a39a80-042a-11ea-9bd9-3005f0dc7799.png)

The figure is on a debug mode which applied the earth with a texture mapping directly from Noise value

**Comment by zhufyaxel** [comment]
Also wondering if there is any recommendation or requirement for generating the random gradient for Perlin Noise?

**Comment by abhimadan** [comment]
The "improved" noise adds continuity at the second derivative of the noise function, so it'll look smoother at the boundaries of each voxel. The random vectors at each of the lattice points are generated in `random_direction.glsl`, which has the following comment:
https://github.com/alecjacobson/computer-graphics-shader-pipeline/blob/d15bc441fcec67d7b467b38cdac6860b28fb572b/src/random_direction.glsl#L5-L6

**Comment by zhufyaxel** [comment]
I found the issue in my implementation. Perlin Noise should not have that performance in general
